name: clean_pattern
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  dio: ^4.0.6
  pretty_dio_logger: ^1.2.0-beta-1
  shared_preferences: ^2.0.15
  logger: ^1.1.0
  equatable: ^2.0.3

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

